### ISSUE TITLE
Resolving imports paths with enabled preloaders

### ISSUE THREAD

**Issue by alexkuz** [gaearon/babel-plugin-react-transform#12]
If I have a preloader in `webpack.config`, such as:
```
preLoaders: {
    { test: /\.jsx?$/, loader: 'eslint', exclude: /node_modules/ }
}
```
then the loader's filename is included in filepath (`/Users/.../eslint-loader/index.js!/Users/.../Component.jsx`). I guess we should split filepath with `"!"` and use the last part of it.

**Comment by gaearon** [comment]
Seems very specific to Webpack, while the plugin isn't related to it per se.
Any other ideas?

**Comment by alexkuz** [comment]
May be there are some other, more reliable parameters in `file`, I can investigate it later

**Comment by alexkuz** [comment]
@gaearon turned out it's kinda `babel-loader`'s fault. It seems it should provide original resource path instead of making concatenated path (see discussion here https://babeljs.slack.com/messages/plugins/)

**Comment by gaearon** [comment]
Is this same as https://github.com/gaearon/react-transform-boilerplate/issues/15?

**Comment by alexkuz** [comment]
yeah, looks like it is

I guess we should file an issue to `babel-loader` and ask if we could replace this call with a plain file path

https://github.com/babel/babel-loader/blob/master/index.js#L31

**Comment by gaearon** [comment]
I'm sure they'll appreciate a PR!

**Comment by gaearon** [comment]
Closing, as it's not actionable here.
