### ISSUE TITLE
Explore wrapping HOCs at the call site

### ISSUE THREAD

**Issue by gaearon** [gaearon/babel-plugin-react-transform#18]
While this sounds pretty crazy, we might want to (via opt-in API?) signal that a particular function in a particular module produces a component, so that the results of this function are identified as components *at the call site*.

On the other hand maybe this is a terrible idea.

**Comment by kgdev** [comment]
Any updates?

**Comment by gaearon** [comment]
Nah, this would be weird. #26 is a better solution to the same problem.

**Comment by gaearon** [comment]
This is fixed in [React Hot Loader 3](https://github.com/gaearon/react-hot-boilerplate/pull/61).
It is built with lessons learned from both React Hot Loader and React Transform.
It’s still in alpha but I encourage you to [check it out](https://github.com/gaearon/react-hot-boilerplate/pull/61)!

**Comment by gaearon** [comment]
>Nah, this would be weird.

Weird or not, this is exactly how we solved it. 😄
