### ISSUE TITLE
`displayName` is not populated during transformation of `React.createClass`

### ISSUE THREAD

**Issue by joshuahhh** [gaearon/babel-plugin-react-transform#24]
## Before react-transform
```
babel.transform('var Component = React.createClass({fun: "yay"});');
```
generates
```
"use strict";

var Component = React.createClass({
  displayName: "Component",
  fun: "yay" });
```
(which includes the populated `displayName`).

## After react-transform
```
babel.transform('var Component = React.createClass({fun: "yay"});', {
    plugins: ['react-transform'],
    extra: {
        'react-transform': []
    }
});
```
generates
```
"use strict";

var _components = {
  _$Unknown: {}
};

function _wrapComponent(uniqueId) {
  return function (ReactClass) {
    return ReactClass;
  };
}

var Component = _wrapComponent("_$Unknown")(React.createClass({ fun: "yay" }));
```
(which does not have a `displayName`).

Using this latter code, dev tools can't get a name for `Component`.

Is this expected? Am I missing something? Thanks!

## Versions
```
├── babel@5.8.23
└── babel-plugin-react-transform@1.0.5
```

**Comment by gaearon** [comment]
https://github.com/gaearon/babel-plugin-react-transform#limitations:

>When using `React.createClass()` and allowing `babel` to extract the `displayName` property you must ensure that [babel-plugin-react-display-name](https://github.com/babel/babel/tree/development/packages/babel-plugin-react-display-name) is included before `react-transform`. See [this github issue](https://github.com/gaearon/babel-plugin-react-transform/issues/19) for more details.

**Comment by joshuahhh** [comment]
Ah, I see. That makes sense now. Thanks for the help!
