### ISSUE TITLE
Check all exports for being React components

### ISSUE THREAD

**Issue by gaearon** [gaearon/babel-plugin-react-transform#26]
Currently exports are not being checked. This is, in a way, a regression from React Hot Loader which used to check every export for componentish-ness. It's hitting us really bad in some cases: 

* https://github.com/rackt/redux/issues/782
* https://github.com/rackt/react-redux/issues/115

#18 could potentially fix this, but I have no idea how to even get started on it without a dependency graph, so in the meantime, we should implement exactly what React Hot Loader did: check every export for being a component.

**Comment by thejameskyle** [comment]
Oh man, I have no idea how to do this that isn't going to cause a mess of other problems.

**Comment by gaearon** [comment]
What kind of problems? This is exactly how React Hot Loader currently works, and it's pretty stable.

**Comment by thejameskyle** [comment]
You'll have to explain how it works, I would check the tests in the react-hot-loader repo but you don't have any... :for_shame:

**Comment by jedwards1211** [comment]
@thejameskyle it's just a development tool dude, not for production

**Comment by thejameskyle** [comment]
I understand that _dude_, development tools need tests too.

**Comment by gaearon** [comment]
Actually that's exactly why this project was started. It was easier to split RHL into several different projects than to write tests for it :-) RHL just [enumerated every key in `module.exports` and wrapped whatever looks like a React component.](https://github.com/gaearon/react-hot-loader/blob/4d5acbf6b329bf1f8df41be2922f1feb042175b9/makeExportsHot.js#L16-L44) This is what I suggest to do here: wrap every export into a conservative runtime check. The wrapping function would be like

```js
let wrappedComponents = [];

wrapExport(something) {
  if (
    something &&
    something.prototype &&
    something.prototype.isReactComponent && // only finds Component descendants but good enough
    wrappedComponents.indexOf(something) === -1 // don't wrap twice
  ) {
    wrappedComponent.push(something); // normal generated code would also need to do that 
    return wrapJustLikeWeWrapInGeneratedCode(something);
  }
  return something; // not an export we should hijack
}
```

Then *every* `export` would go through this wrapper, regardless of what's in there.
Does it make sense?

This is a runtime check but it's important for many cases where we want export a React class generated by some factory in another file, and it's essential to maintain its identity.

**Comment by redwoodfavorite** [comment]
+1 Would like to see this.

I am actually working on a backbone/react application and using the `react-hmre` preset.  This is causing `react-proxy` to run on our backbone views which is an issue!

**Comment by gaearon** [comment]
Interesting, can you show code that fails? In s separate issue.

**Comment by redwoodfavorite** [comment]
@gaearon will do.

**Comment by mmakarin** [comment]
https://github.com/gaearon/react-transform-catch-errors/issues/25

**Comment by gaearon** [comment]
This is fixed in [React Hot Loader 3](https://github.com/gaearon/react-hot-boilerplate/pull/61).
It is built with lessons learned from both React Hot Loader and React Transform.

I’m closing the issue as unsolvable in this repo.
