### ISSUE TITLE
support component factory methods

### ISSUE THREAD

**Issue by aaronjensen** [gaearon/babel-plugin-react-transform#3]
Many of our legacy components are created with `componentFactory({...})` instead of `React.createClass`. Ideally it'd support any factory function name.

**Comment by gaearon** [comment]
Fair! Want to make a pull request? We can change `react-transform` options to be an object with `transforms` array and optional `factoryMethods` array. By default `factoryMethods` is `['React.createClass']` but you can change it to `['React.createClass', 'componentFactory']` or even `['componentFactory']`.

In the source, [this code](https://github.com/gaearon/babel-plugin-react-transform/blob/2664f352c2f224c3ce45983d291d21c1399b675c/src/index.js#L43-L51) would be changed to look at the plugin options. [Here's](https://github.com/gaearon/babel-plugin-react-transform/blob/2664f352c2f224c3ce45983d291d21c1399b675c/src/index.js#L269) how we read plugin options.

**Comment by gaearon** [comment]
Let's discuss in https://github.com/gaearon/babel-plugin-react-transform/issues/8.
