### ISSUE TITLE
Github link for babel-plugin-react-display-name in README leads to 404

### ISSUE THREAD

**Issue by kevinold** [gaearon/babel-plugin-react-transform#31]
It appears the project no longer lives at https://github.com/babel-plugins/babel-plugin-react-display-name even thought the npm page is still there https://www.npmjs.com/package/babel-plugin-react-display-name.

I believe this would be the "official" version of the package now but wanted to ask before submitting a PR: https://github.com/gajus/babel-plugin-react-display-name

**Comment by gaearon** [comment]
AFAIK the official page should be inside `babel/babel` monorepo.
