### ISSUE TITLE
Supporting ES module imports

### ISSUE THREAD

**Issue by guybedford** [gaearon/babel-plugin-react-transform#35]
@gaearon thanks for offering to help before. From the previous issues I think the interop issue @timbur is having is that the component module is of the form `{ default: component }` for ES modules when they are added to the imports by the transformer instead of the direct component.

Babel has an exception where a module with a single default export gets treated as the entire module, but I don't think we can't assume this exception for real ES module environments.

A check before handling the component of something like `component instanceof React.component ? component || component.default || component` may be a way to support ES module react components here. I know the `instanceof` doesn't quite cover it though so let me know if you have any ideas here?

Let me know your thoughts and if that is clear.

**Comment by timbur** [comment]
@guybedford Thanks for your time on this stuff, as always.  :)

Might the best solution actually be to revisit https://github.com/babel/babel/issues/2148?  Or I'm I wrong in thinking that the algorithm you described there would solve this issue and all others like it?  Regardless, it seems to me like there *must* be some way to determine whether a module was originally ES6, and if so and if it's imported into a CJS module (or another transpiled ES6 module with `default` specified of course), then use the `default` rather than the entire ES6 module object.

**Comment by guybedford** [comment]
@timbur sure no problem, it's a good use case to cover.

I think the issue here is actually just that the `file.addImport` API call to Babel needs to access the `default` export to be like `import x from 'x'` instead of `import * as x from 'x'` for correct interop, which should then handle the use case completely fine. This may or may not be a Babel issue underneath, I'm not completely sure yet.

**Comment by gaearon** [comment]
When you come to a conclusion let me know and I'll happily add a workaround you think is right.

**Comment by timbur** [comment]
> I think the issue here is actually just that the file.addImport API call to Babel needs to access the default export to be like import x from 'x' instead of import * as x from 'x' for correct interop

Ohh I see.  That makes the most sense and could be exactly the problem.

**Comment by guybedford** [comment]
Sure thanks, I've posted https://github.com/babel/babel/issues/2496.

**Comment by guybedford** [comment]
Just to update here - apparently `addImport` isn't a public API. The issue here is definitely with that function not handling the interop scenarios.

**Comment by gaearon** [comment]
I think that actually if I use `file.addImport` directly (effectively reverting d4c90c764cf9d91cc217601d53c28b8b41108d9b) it will work as you described. Can you confirm this is the change you need?

**Comment by timbur** [comment]
@gaearon No, it still imports the entire module object rather than the `default`.

**Comment by timbur** [comment]
I thought maybe I could use a JSPM override to make it work but no, d4c90c764cf9d91cc217601d53c28b8b41108d9b definitely breaks it by importing the entirely module object rather than the module's `default` export.

**Comment by gaearon** [comment]
So will reverting it help? I can do that.

**Comment by timbur** [comment]
Yeah reverting it fixed the problem for me.

**Comment by gaearon** [comment]
I think this is probably fixed because we [no longer use `absolute` in the source](https://github.com/gaearon/babel-plugin-react-transform/blob/827843e1da56b1edbd4f9e526339d9968ada652d/src/index.js#L284).
Please reopen if still an issue.
