### ISSUE TITLE
Hot loading doesn't work when using Relay

### ISSUE THREAD

**Issue by idris** [gaearon/babel-plugin-react-transform#39]
Since I started using Relay, hot loading always gives the error
```
[HMR] The following modules couldn't be hot updated: (They would need a full reload!)
```

The issue is also mentioned in fortruce/relay-skeleton#1, but I don't think that solution is a good way to go.

**Comment by gaearon** [comment]
Please show the specific project.
This error happens if the top-level update bubbles to a non-component file.
It's not related to Relay—it's related to how you structure your project.

**Comment by gaearon** [comment]
This is also wrong repository to report this.
Babel plugin doesn't know anything about hot reloading.
Let's discuss in https://github.com/gaearon/react-transform-hmr or https://github.com/gaearon/react-transform-boilerplate.
