### ISSUE TITLE
[React Transform HMR] Patching _$Unknown when using ES6 classes with default export

### ISSUE THREAD

**Issue by okonet** [gaearon/babel-plugin-react-transform#40]
When using `export default class extends React.Component` syntax, `[React Transform HMR] Patching _$Unknown` in being displayed in the console instead of the component name.

<img width="688" alt="2015-10-20 at 00 43" src="https://cloud.githubusercontent.com/assets/11071/10593391/b222325a-76c3-11e5-8fae-6c930d6b26f7.png">

vs

<img width="691" alt="2015-10-20 at 00 43" src="https://cloud.githubusercontent.com/assets/11071/10593409/da2447d4-76c3-11e5-956f-5e3d93786670.png">

The second one is defined like `export default class ImageUploadDropzone extends React.Component`

Also I see a lot of `_default` when getting `propTypes` warnings. Not sure if this is related to the other issue.

<img width="698" alt="2015-10-20 at 00 43" src="https://cloud.githubusercontent.com/assets/11071/10593420/f21271a4-76c3-11e5-9eea-227b679bad71.png">

I'm using React 0.14 and `babel-plugin-react-transform@1.1.1`

**Comment by gaearon** [comment]
If it's an anonymous class, I'd say it's expected, isn't it?
Does the class name somehow get inferred without this plugin?

**Comment by okonet** [comment]
Well, in this case it should be a file name. At least this is how Babel infers displayNames into it: https://babeljs.io/docs/usage/jsx/

**Comment by gaearon** [comment]
Did you add Babel displayName plugin before React Transform? Maybe it runs by default but is disabled when you specify plugins explicitly. 

In the README we mention that you need to put it before React Transform if you want its behavior.

**Comment by okonet** [comment]
Yes, it's there but I believe that this '_default' issue might be somehow related to this plugin.

**Comment by okonet** [comment]
I'm closing this one, since it seems inferring `displayName` from filename doesn't work with ES2015 classes: https://phabricator.babeljs.io/T1331
