### ISSUE TITLE
How to combin with an existing server

### ISSUE THREAD

**Issue by sotayamashita** [gaearon/babel-plugin-react-transform#42]
I use Tomcat server and is there any way to combine them ?

**Comment by sotayamashita** [comment]
babel-plugin-react-transform just compile js file to other server like webpack dev server ? 
http://webpack.github.io/docs/webpack-dev-server.html#combining-with-an-existing-server

**Comment by joaovpmamede** [comment]
I'm having the same problem, well not exactly the same problem what happens is that I get a notification on console:

```
HMR] Checking for updates on the server...
(program):81 [React Transform HMR] Patching StatsWidget
(program):20 [HMR] Updated modules:
(program):22 [HMR]  - 787
(program):41 [HMR] App is up to date.
```

but then nothing happens (no "reload").
Everything was running smoothly with react-hot-loader though.


**webpack config:**

```
config.entry.unshift('webpack/hot/only-dev-server');
config.entry.unshift('webpack-dev-server/client?http://0.0.0.0:8081/');

config.devServer = {
  hot: true,
  inline: true
};
```

**Comment by zhbhun** [comment]
Backend server on `locahost:8080`, webpack-middle-server on `localhost:3000`, when change code, hot-module-replace request address is `http://localhost:8081/__webpack_hmr`, is any config can change this?

**Comment by zhbhun** [comment]
Oh! Config is in `webpack-hot-middleware`, not `babel-plugin-react-transform`? You need add path option to `webpack-hot-middleware/client`, like `webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr`.

**Comment by gaearon** [comment]
Hi folks! Alas, this discussion is not relevant to this repo. Anything concerning the servers is best asked in Webpack or https://github.com/glenjamin/webpack-hot-middleware repos or chats. This repo is just for plugin that locates React components and wraps them—it’s not even related to hot reloading.

That said,

>Fixed: I had an error on my code, but apparently the server still receives and notify the file changes.

>Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or **you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).**

I highlighted the relevant part: most likely you have multiple Reacts in the bundle. Check with `npm ls react` and remove the extra ones.
