### ISSUE TITLE
Babel 6

### ISSUE THREAD

**Issue by aruberto** [gaearon/babel-plugin-react-transform#46]
[Babel 6](http://babeljs.io/blog/2015/10/29/6.0.0) was just released and has a new plugin API. Assuming this plugin will need to be updated to support it (otherwise can just close this issue).

**Comment by leecade** [comment]
:+1:  want this

**Comment by theneva** [comment]
:+1:

**Comment by anselmo** [comment]
+1

**Comment by gaearon** [comment]
Please, don't +1 the issue, it doesn't help at all.
I'm aware Babel 6 is out and I'll support it in the next release.
If you feel like making a PR or temporarily maintaining a Babel 6-compatible fork, please do.
I will get back to this (and React 0.14 full support) in a week or two, in the meantime please be patient.

**Comment by theneva** [comment]
I'm trying to make a PR, but can't for the life of me figure out where `babel-plugin` has gone.

It's used by the `build` npm script, but is no longer part of `babel`. It doesn't seem to be part of `babel-core`, `babel-cli`, or even `babel-runtime`, and there's no package called just `babel-plugin`. Am I missing something obvious?

As you can probably tell, this is my first attempt at babel plugins, so I'm not familiar with the ecosystem...

**Comment by gaearon** [comment]
It's not really important, from what I remember. I just copied it because that's what other plugins were using, but I think it can be replaced by simple babel CLI call. You can take inspiration from any Babel plugin here: https://github.com/babel/babel/tree/development/packages.

**Comment by theneva** [comment]
Thanks, will look into it and report back if/when I have something.

**Comment by chicoxyzzy** [comment]
I've made some progress on this
branch: https://github.com/chicoxyzzy/babel-plugin-react-transform/tree/babel-6
commit: https://github.com/gaearon/babel-plugin-react-transform/commit/292e5ad3c825d98ed4116cb56fb3fc722df5460f
If you `npm link` my `babel-6` branch you can see that visitor's `exit` method still returns result of `t.program`. I can't find any docs on how to fix this method to work proper.
Also tests are still on Babel 5 so they won't work either.
@theneva do you have any progress on this?

**Comment by chicoxyzzy** [comment]
options should be passed like so
```
          presets: ['es2015', 'react'],
          plugins: [
            ['transform-object-rest-spread'],
            ['transform-class-properties'],
            ['react-transform', {
              transforms: [
                {
                  transform: 'react-transform-hmr',
                  imports: ['react'],
                  locals: ['module'],
                }, {
                  transform: 'react-transform-catch-errors',
                  imports: ['react', 'redbox-react'],
                },
              ],
            }],
          ],
```

**Comment by leecade** [comment]
@chicoxyzzy thanks , I didn't know how to add `extra` before

**Comment by theneva** [comment]
Nice, @chicoxyzzy. I haven't been able to get very far, no – and I unfortunately can't get around to look any more into it before tomorrow. Please keep up your good work :smile:

**Comment by gaearon** [comment]
We should make a Babel 6 preset for HMR + error catching.

**Comment by danmartinez101** [comment]
Just threw it together and haven't test yet but: https://github.com/danmartinez101/babel-react-hmre

Is this on the right track, @gaearon ?

**Comment by chicoxyzzy** [comment]
Yep @danmartinez101 it looks ok.

But first of all we need to:
- migrate build step to Babel 6
- update tests
- fix `Program.exit`

I'll try my best to fix it but I'll be very busy next two weeks. Anyway feel free to ping me if you think I can help.

**Comment by buildmaster** [comment]
I've created a pull request on chicoxyzzy/babel-plugin-react-transform#babel-6 which updates the tests to use babel 6. All but the Vanilla test on that branch now throw an error 
```
Unexpected return value from visitor method function (path) {
        return fn.call(state, path, state);
      }
```

**Comment by chicoxyzzy** [comment]
@buildmaster I just checked your PR. If you will `rm -rf node_modules` and then `npm install` you'll see error
```
> babel-plugin-react-transform@1.1.1 build /Users/Chico/Projects/babel-plugin-react-transform
> babel-plugin build

sh: babel-plugin: command not found
```

that's because there is no `babel-plugin` in `node_modules/.bin` directory anymore. So we should fix `build` script in `package.json` somehow

**Comment by buildmaster** [comment]
ok I've copied the command from the old babel-plugin bin, but means a dev requirement on babel-cli as well.

**Comment by buildmaster** [comment]
ok made a couple of updates, but I think I'm at the limit of my knowledge, so might have to wait for someone who knows how the plugin actually works to pick up the fix

**Comment by theneva** [comment]
@buildmaster @chicoxyzzy I think this is the easiest way to do it, yeah – that's how I did it in my (still unpushed) branch too. Not sure you need the [`--copy-files`](https://github.com/chicoxyzzy/babel-plugin-react-transform/pull/1/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R25) option, though? 

At any rate, this will be quite a bit bigger than simply changing the plugin export… especially due to fixing the tests, which I don't have any experience with.

Is anyone close to having a complete PR on this?

**Comment by TaopaiC** [comment]
Hi I updated some files based on @chicoxyzzy 's and @buildmaster 's work.  PR is at chicoxyzzy/babel-plugin-react-transform/2 . 

since the generated sources changed, need experts to review.
three of four test cases look fine, but test/fixtures/classic is still failed. If enabling decorator in babel, the error message is same as babel/babel#2645 and babel/babel#2801 .

**Comment by chicoxyzzy** [comment]
Good work @TaopaiC and @buildmaster! I've merged your commits! Now we should fix `Program.exit` and failing test for modern classes

**Comment by chicoxyzzy** [comment]
@gaearon should I create WIP PR so everyone will be able to help and track progress more comfortably?

**Comment by geminiyellow** [comment]
is any news in here?

**Comment by gaearon** [comment]
Please feel free to create a PR.
I will be able to review in a couple of weeks and no sooner due to my current workload.

**Comment by chicoxyzzy** [comment]
> Please feel free to create a PR.

here it is #48

**Comment by danmartinez101** [comment]
I have no idea how babel or this plugin work so I'm going to start hacking away in a different fork for now. 
You can find it here: https://github.com/danmartinez101/babel-plugin-react-transform/tree/unit-tests

This is the approach I'm planning on taking:
1. Write granular unit tests for the existing plugin (with Babel 5)
2. Upgrade to Babel 6
3. Fix the granular unit tests
4. Update the fixtures
5. Hope that the fixture-based tests pass because the unit tests covered all the logic

Once I get through all or most of this, I can either apply what I've learned to the branch created above, or we can just go with this one ( assuming that it actually works, of course... and that is a big assumption :P )

**Comment by gaearon** [comment]
Just throwing in this amazing new reference: https://github.com/thejameskyle/babel-plugin-handbook
We did some things in a wrong way because I didn't know any better.
While we're at it, we can learn to use `scope` correctly, etc.

**Comment by danmartinez101** [comment]
I started reading that last night; it has help a lot already :D :D I was planning on seeing if parts of the plugin could be improved, but want to get through tests and upgrade first to make sure I really understand it. I'm hoping to get it wrapped up tonight.

**Comment by danmartinez101** [comment]
I'm also thinking that https://github.com/babel/babel/tree/master/packages/babel-template is going to be useful here.

**Comment by justingreenberg** [comment]
@danmartinez101 for sure—`babel-template` is being used to [create the core HOCs](https://github.com/chicoxyzzy/babel-plugin-react-transform/blob/babel-6/src/index.js#L3) (as a workaround for decorators) in #48 and there are definitly some other areas i think templating could simplify things

@gaearon what do you think is wrong with respect to scope?

**Comment by vagusX** [comment]
how's it going?

**Comment by mmahalwy** [comment]
any luck with this?

**Comment by gaearon** [comment]
Please track #50 instead. I will soon have time to release it & related packages.

**Comment by kaizvn** [comment]
I've met issue with missing extra option for `react-transform`, but I found out how to fix it. Hope this can help

```
{
  "presets": [
    "es2015",
    "react"
  ],
  "env": {
    "development": {
      plugins: [
        ['react-transform', {
          transforms: [
            {
              transform: 'react-transform-hmr',
              imports: ['react'],
              locals: ['module'],
            }, {
              transform: 'react-transform-catch-errors',
              imports: ['react', 'redbox-react'],
            },
          ],
        }],
      ]
    }
  }
}
```
