### ISSUE TITLE
TypeError: Plugin is not a function

### ISSUE THREAD

**Issue by phaistonian** [gaearon/babel-plugin-react-transform#51]
Any idea how to resolve or what's causing this?

```
ERROR in ./js/index.js
Module build failed: TypeError: Plugin is not a function
    at exports.default (/Users/phaistonian/www/Test/node_modules/babel-plugin-react-transform/lib/index.js:258:10)
```

**Comment by thejameskyle** [comment]
You are using this plugin with Babel 6, but the newest version has not been published.

Please see: https://github.com/gaearon/babel-plugin-react-transform/pull/50#issuecomment-162947977

**Comment by vicentedealencar** [comment]
I've been following #50, and I am using 2.0.0-beta1

I see the error: `Module build failed: TypeError: Plugin is not a function`

Looking further on the error line on `./node_modules/babel-plugin-react-transform/lib/index.js`
`return new Plugin('babel-plugin-react-transform', {`

Maybe I have still some left overs from react-hot-loader

**Comment by thejameskyle** [comment]
@vicentedealencar That line does not exist in 2.0.0-beta.1, you must still have 1.x installed.

**Comment by PabloRosales** [comment]
In case someone comes here, I had this problem, removed my 1.1.1 from node_modules and run as indicated on the Readme:

npm install --save-dev babel-plugin-react-transform@beta

Solves it for me.

**Comment by vicentedealencar** [comment]
ops, my bad. thanks

**Comment by natac13** [comment]
@PabloRosales +1! Thanks so much
