### ISSUE TITLE
Release version number / react-transform-boilerplate update

### ISSUE THREAD

**Issue by justingreenberg** [gaearon/babel-plugin-react-transform#54]
@thejameskyle @gaearon what are you guys thinking for release version—`1.2.0` or `2.0.0`?

we should probably get **gaearon/react-transform-boilerplate#64 merged with this release**, since it's mentioned throughout this repo and is the reference implementation using babel 6—docs are updated and everything *should* be good to go. 

james, if you have a sec can you review and/or (maybe dan) can merge later? i just have to rebase with new version of babel-plugin-react-transform, so let me know what i should use :smile:

**Comment by thejameskyle** [comment]
It has to be a major release because it requires a new version of Babel.

I'll take time and review everything this evening after work. When I publish the prerelease it'll be good to update that PR. If you aren't around I'll just merge it and update it in the repo.

**Comment by justingreenberg** [comment]
Sounds good—thank you

**Comment by justingreenberg** [comment]
thanks again for everything
