### ISSUE TITLE
Module build failed: ReferenceError: Unknown plugin "react-transform" specified

### ISSUE THREAD

**Issue by vagusX** [gaearon/babel-plugin-react-transform#56]
Known that this repo has updated, I installed this repo via git@github.com:gaearon/babel-plugin-react-transform.git and the lib/index.js is empty

**Comment by hbin** [comment]
+1

**Comment by thejameskyle** [comment]
You cannot install via GitHub. As mentioned elsewhere, I plan to publish a prerelease to npm in a few hours.
