### ISSUE TITLE
Does react-transform support updating the target file dynamically as well?

### ISSUE THREAD

**Issue by AjayKumarJ** [gaearon/babel-plugin-react-transform#65]
I have tried the react-transform-boilerplate, it is really awesome. Is there any way I could see the changes the target folder as well when I make a change.
Currently, when I make any change it bundles it and directly updates in the server. Instead, I want to see the changes in the file (static/bundle.js) directly using (Finder and text editor). 

This case, I can commit or take a reference of the bundle.js for the further use.

Thanks in advance.

**Comment by razh** [comment]
This issue pertains to webpack and not this plugin. This plugin only transforms syntax.

Relevant issue: https://github.com/webpack/webpack-dev-server/issues/62

**Comment by gajus** [comment]
@AjayKumarJ You can make it write to the disk using a webpack plugin, https://github.com/gajus/write-file-webpack-plugin.
