### ISSUE TITLE
release 2.0.0

### ISSUE THREAD

**Issue by chicoxyzzy** [gaearon/babel-plugin-react-transform#66]
I use `babel-plugin-react-transform` everyday and had no issue since `beta1` was released. So just curious when 2.0.0 will be released. I believe master is stable enough. Or is there are any blockers?

**Comment by thejameskyle** [comment]
I keep telling myself I'm going to do it and then not doing it.

FUCK IT WE DO IT NOW!

**Comment by thejameskyle** [comment]
DONE!!!
