### ISSUE TITLE
displayName

### ISSUE THREAD

**Issue by thejameskyle** [gaearon/babel-plugin-react-transform#67]
Alright, this has been a common issue so I'm folding every other issue into this one single one.

Basically since in Babel 6 plugin visitors get merged, this plugin will always run before `babel-plugin-transform-react-display-name`, meaning that `displayName` will never get added because we've already changed the AST.

The fix here has to be inside of the `displayName` plugin so that it is forced to run before any other transforms.

I'm locking this issue because I don't want any unnecessary noise, I've already identified the problem.

**Comment by thejameskyle** [comment]
https://github.com/babel/babel/pull/3216

**Comment by gaearon** [comment]
Good. So we can close this after next Babel release?

**Comment by thejameskyle** [comment]
Yeah
