### ISSUE TITLE
Add configuration for which transforms to run in production

### ISSUE THREAD

**Issue by gaearon** [gaearon/babel-plugin-react-transform#7]
Right now, transforms have to include special code to opt out of production effect. Even if they are no-ops, the code to *call* them is still generated, and any `imports` are still imported.

I think we should change this behavior:

* All transforms should be turned off by default in production
* Transform configuration may have an opt-in `production: true` which enables it in production
* If there are no transforms enabled in production, we don't generate the component records and related code, as there is nothing to consume it

**Comment by gaearon** [comment]
Maybe we can solve this on Babel configuration level.
See `env` option in `.babelrc`: https://babeljs.io/docs/usage/babelrc/

**Comment by gaearon** [comment]
For example, a config could look like this:

```js
{
  "optional": ["runtime"],
  "stage": 0,
  "env": {
    "development": {
      "plugins": ["react-transform"],
      "extra": {
        "react-transform": [{
          "target": "react-transform-webpack-hmr",
          "imports": ["react"],
          "locals": ["module"]
        }, {
          "target": "react-transform-catch-errors",
          "imports": ["react", "redbox-react"]
        }]
      }    
    }
  }
}
```

You'd need to compile your project with `NODE_ENV=production`, for example:

```
NODE_ENV=production webpack --config webpack.config.production.js
```

(Unix)

or

```
set NODE_ENV=production && webpack --config webpack.config.production.js
```

(Windows)

**Comment by chrishoage** [comment]
I can confirm that using the babel env option works exactly as expected. No changes required at all.

**Comment by amccloud** [comment]
using env works for me too

**Comment by ameensol** [comment]
here to confirm redundantly that babel env also worked for me

**Comment by gaearon** [comment]
Closing, as it's not our responsibility.

Users can either use `.babelrc` or put the configuration into `query` option (it can be an object!) of Webpack `babel-loader` configuration.
