### ISSUE TITLE
Entire application is reloading with message "Navigated to..."

### ISSUE THREAD

**Issue by ccoffey** [gaearon/babel-plugin-react-transform#70]
When I make any change to a React component in my project, I see the following in Chrome's dev-tools console and then my entire application reloads.

How do I stop the entire application from reloading? I'm guessing it has something to do with the final statement "Navigated to http://localhost:9000/frame.html" but I have no idea why this is happening.

```
[WDS] App updated. Recompiling...
[WDS] App updated. Reloading...
Navigated to http://localhost:9000/frame.html
```

Edit: I forgot to mention that my application lives inside an iframe and in order to get React dev-tools to work I had to do something like the following: https://gist.github.com/jaredly/593c9b22c619aaf0e0cf. Perhaps this information is relevant?

**Comment by gaearon** [comment]
If you use webpack-hot-middleware, please try using vanilla WebpackDevServer instead. If the issue persists please file it with WebpackDevServer. This plugin has no relation to the actual hot reloading mechanism implemented by Webpack.
