### ISSUE TITLE
iframes and custom webpack loaders

### ISSUE THREAD

**Issue by ccoffey** [gaearon/babel-plugin-react-transform#72]
For the past few days I've been struggling to integrate *babel-plugin-react-transform* with a project that lives in an iframe. I have [forked react-transform-boilerplate](https://github.com/ccoffey/react-transform-boilerplate/commit/417dee9e4fca10a1c839e13c2859f3782858644a) and made the minimum number of changes necessary to reproduce the problem I am experiencing.

Two things about this project that might be causing the problem
 1. This project must live inside an iframe,
 2. Because of the iframe we need to use a custom webpack loader [entry-loader](https://www.npmjs.com/package/entry-loader)

**The problem:** Now when I make a change to a React component I see the following in dev-tools and no hot-loading happens.

```
[HMR] connected
client.js?3ac5:106 [HMR] bundle rebuilding
client.js?3ac5:108 [HMR] bundle rebuilt in 304ms
```

**Comment by gaearon** [comment]
Hi! You will probably have better luck asking this in Webpack issues or chats. This plugin is just concerned with wrapping React components—it has no relation to either HMR or Webpack. Unfortunately I don’t know how to help you either because I’m not experienced with iframes in Webpack.
