### ISSUE TITLE
array-find issue

### ISSUE THREAD

**Issue by morlay** [gaearon/babel-plugin-react-transform#73]
Since babel@6.4, they will not include polyfills, but other shims like `collections` will be used in process scope ( babel-polyfill will overwrite them before )

https://github.com/montagejs/collections/issues/139

It will broken `matchesPatterns`, because of
```
!!-1 // return true
```

Just notice it,  if someone use webpack with other packages, the global shim will make babel-plugin-react-transform broken

**Comment by gaearon** [comment]
Thanks for reporting. This is a pretty ugly situation because no build tool should ever put polyfills (especially broken ones!) in the global scope. However I agree it’s best that we work around this.

**Comment by gaearon** [comment]
This is fixed in 2.0.2.
