### ISSUE TITLE
Use without .babelrc

### ISSUE THREAD

**Issue by IanVS** [gaearon/babel-plugin-react-transform#74]
I'm creating a set of reusable react components, and having a `.babelrc` file is problematic, so I would like to avoid having one if possible.  I cannot figure out how to translate the option objects for `transforms` into a cli-friendly format.  Can this be used without a `.babelrc`, and if so, how?

**Comment by thejameskyle** [comment]
You *should* be using a `.babelrc` file, I have yet to hear a reason its not possible.

**Comment by IanVS** [comment]
I certainly would like to use a `.babelrc`, except that I've found that if a library has one, the consuming app will try to use it ([see this issue](https://github.com/facebook/react-native/issues/4062)).  In my development model, I want to use `npm link` and work concurrently in the library and consuming project rather than frequently publishing to npm, so I can't just add it to my `.npmignore`.  Or, I may move the whole library into my consuming app, but it will still need a unique babel configuration.  If you have suggestions of how I could continue using a `.babelrc`, I'd love to know how.

**Comment by danmartinez101** [comment]
@IanVS You and use the babel presets on the cli pretty easily to support your specific use case here. 

You can use https://github.com/danmartinez101/babel-preset-react-hmre as an example.

Then just `babel --presets react-hmre` or `babel --presets your-version`

**Comment by IanVS** [comment]
@danmartinez101, nice!  That looks perfect, thank you.
