### ISSUE TITLE
React transforms being run on Backbone views

### ISSUE THREAD

**Issue by redwoodfavorite** [gaearon/babel-plugin-react-transform#78]
This issue seems to be closely related to https://github.com/gaearon/babel-plugin-react-transform/issues/26

Basically I ran into this issue where I would get a `TypeError` in a Backbone constructor only when I was running our hot config.   The constructor for this backbone view is on the prototype of another view and was being used like this:

```const someView = new this.SomeViewConstructor();```

Turns out the context in `SomeViewConstructor` was a `proxiedMethod`.  Apparently this constructor is being wrapped by `react-proxy` even though this module did not export a react component.

**Comment by gaearon** [comment]
Can you show the relevant code?

**Comment by redwoodfavorite** [comment]
@gaearon So it's in a private repo but I made a more isolated case here: https://github.com/redwoodfavorite/react-backbone-hmr

I couldn't actually recreate the issue until I put a `render` method on the Backbone view!

**Comment by redwoodfavorite** [comment]
Which, as you might know, is a standard in Backbone too!

**Comment by gaearon** [comment]
This looks like a problem with an overly broad check in https://github.com/gaearon/babel-plugin-react-transform. Can you please file it there? The best way to file it would be with a failing test but if you don't have time just creating the issue with a link to your project would be great.

**Comment by mattijauhiainen** [comment]
We are having similar problem with ember. Opened an issue for it here https://github.com/gaearon/babel-plugin-react-transform/issues/81

**Comment by gaearon** [comment]
I think I know what the problem is.
Fix is welcome: https://github.com/gaearon/babel-plugin-react-transform/issues/84#issuecomment-185472925

**Comment by gaearon** [comment]
Should be fixed in 2.0.1.
