### ISSUE TITLE
Question: Is it a bad practice to use react-transform for production code?

### ISSUE THREAD

**Issue by slestang** [gaearon/babel-plugin-react-transform#79]
All example and documentation seems to be about setting up react-transform only on development mode (with the help of .babelrc _env_ property). But I recently started to use the [Sentry transform](https://github.com/luisrudge/react-transform-sentry) that is clearly made for production code. Their documentation clearly state that they enable react-transform in production.

So I was wondering if they were any impact on my code (I think mostly about perf) about using react-transform for production code?

Related question (but slightly off topic): Does anybody know a way to have a production and development configuration for react-transform in _.babelrc_ without duplicate part between the 2 environment?
My current _.babelrc_ looks like this:
```js
{
  "presets": ["es2015", "react", "stage-0"],
  "env": {
    "development": {
        "plugins": [
          [
            "lodash",
           ["react-transform", {
              "transforms": [
                {
                  "transform": "react-transform-sentry",
                  "imports": ["react"]
                },
                {
                  "transform": "react-transform-hmr",
                  "imports": ["react"],
                  "locals": ["module"]
                },
                {
                  "transform": "react-transform-catch-errors",
                  "imports": ["react", "redbox-react"]
                },
              ]
            }]
          ]
        ]
    },
    "production": {
        "plugins": [
          [
            "lodash",
           ["react-transform", {
              "transforms": [
                {
                  "transform": "react-transform-sentry",
                  "imports": ["react"]
                }
              ]
            }]
          ]
        ]
    }
  }
}
```

**Comment by gaearon** [comment]
>So I was wondering if they were any impact on my code (I think mostly about perf) about using react-transform for production code?

Not really as long as you keep track of what transforms do and how invasive they are. For example, you don't want to enable `react-transform-hmr` in prod because it proxies every method and class making them much slower.
