### ISSUE TITLE
Make React component search configurable

### ISSUE THREAD

**Issue by gaearon** [gaearon/babel-plugin-react-transform#8]
As requested in #3 and #6, let's make component search more flexible and configurable.
I imagine us changing the `react-transform` config to be an object, with `transforms` being an array.

`.babelrc` might look like this:

```js
{
  "stage": 0,
  "plugins": [
    "react-transform"
  ],
  "extra": {
    "react-transform": {
      "transforms": [{
        "transform": "react-transform-webpack-hmr",
        "imports": ["react"],
        "locals": ["module"]
      }, {
        "transform": "react-transform-catch-errors",
        "imports": ["react", "redbox-react"]
      }, {
        "transform": "./src/my-custom-transform"
      }]
    }
  }
}
```

(Note I renamed `target` to `transform`, I think it makes more sense but feel free to disagree.)

This gives us space to add more configuration options. I'd like to add `factoryMethods` to address #3 and `baseClasses` to address #6. If you omit them, we will use the defaults:

```js
"react-transform": {
  "baseClasses": ["React.Component", "Component"], // defaults
  "factoryMethods": ["React.createClass", "createClass"], // defaults
  "transforms": [...]
}
```

However you're free to specify different ones:

```js
"baseClasses": [] // inspect every class with render() instead
"baseClasses": ['React.Component', 'MyCustomBaseComponent'] // inspect specific base classes
"factoryMethods": ["myComponentFactory", "React.createClass"] // inspect specific factory methods
```

etc.

I currently don't have time to do this, but I'm happy to accept a pull request.

**Comment by aaronjensen** [comment]
A stab at this is in #10
