### ISSUE TITLE
Transform(s) to strip propTypes and displayName

### ISSUE THREAD

**Issue by mark-rushakoff** [gaearon/babel-plugin-react-transform#80]
I don't need propTypes or displayName in my production builds. I would like to remove them so my production code is less bloated.

There are at least two standalone NPM packages that strip propTypes, and I wasn't able to find a standalone package that strips displayName.

I don't want to maintain a package for this, but it would be cool if someone from the community were to write one or two plugins to strip propTypes and displayName, and have them integrated with babel-plugin-react-transform, of course.

**Comment by pwmckenna** [comment]
If I understand react-transform correctly, it wraps the discovered components in code that is transforms the component at run time...so using this to strip out code might actually result in a slower/larger production build.

**Comment by gaearon** [comment]
Yeah, this is not something we can do.

**Comment by avindra** [comment]
@mark-rushakoff : I was wondering about this myself, and just published a Babel plugin to the npm registry which does this, [react-strip-proptypes](https://www.npmjs.com/package/react-strip-proptypes).

Give it a shot!

**Comment by turadg** [comment]
FWIW, react-strip-proptypes trimmed my 3,960,805 byte build to 3,888,555 (1.8% smaller).
