### ISSUE TITLE
Future of React Transform

### ISSUE THREAD

**Issue by gaearon** [gaearon/babel-plugin-react-transform#90]
FYI, I published a post today:
https://medium.com/@dan_abramov/hot-reloading-in-react-1140438583bf

**Comment by michael-hertzberg-zocdoc** [comment]
@gaearon i was a big confused by the deprecation notice... i've been personally using this to instrument my React components to send over to a logging service. Still, nothing to do with hot module reloading... am I missing the idea here?

**Comment by gaearon** [comment]
@michael-hertzberg-zocdoc 

The deprecation has nothing to do with hot reloading per se. (I’m just saying that the most common use case for it, hot reloading, is solved by React Hot Loader 3.)

**The reason the project is deprecated is it’s impossible to reliably detect React components at the compile time.** It wasn’t so bad during React 0.13, but functional components in React 0.14 are notoriously hard to detect (#57), and it’s not going to get easier over time. Any function may turn out to be a React component now. Additionally, components that are *generated* (e.g. with higher order components) were not being detected at all.

For instrumenting React components, you will be able to use the official React devtool API that is soon going to be exposed. It’s unstable but it’s better than nothing. (https://github.com/facebook/react/pull/6549, https://github.com/facebook/react/issues/5306)
