### ISSUE TITLE
undefined value static properties outside class

### ISSUE THREAD

**Issue by isman-usoh** [gaearon/babel-plugin-react-transform#95]
undefined value declare static properties set outside class (inside is work)

I use typescript commpile to es6 but static properties out of class 

.babelrc
```
{
  "presets": [ "es2015", "stage-0", "react", "react-hmre"]
}
```

App.js
```
class App extends Component {
    render() {
        console.log(App.Username); // show undefined 
        return (
            <div>
                <h1>Hello {App.Username}</h1>
            </div>
        );
    }
}
App.Username = "MyUsername";
```

**Comment by gaearon** [comment]
Can you please share a complete project reproducing the issue?

**Comment by isman-usoh** [comment]
Source: 
https://github.com/isman-usoh/react-transform-boilerplate/blob/master/src/App.js

**Comment by gaearon** [comment]
FWIW issues like this should disappear completely in [React Hot Loader 3](https://github.com/gaearon/react-hot-boilerplate/pull/61).
It is built with lessons learned from both React Hot Loader and React Transform.
It’s still in alpha but I suggest you to [check it out](https://github.com/gaearon/react-hot-boilerplate/pull/61).

I’ll try to look into why it happens with this project though in a couple of weeks unless somebody beats me to it.
