### ISSUE TITLE
static properties are undefined

### ISSUE THREAD

**Issue by tobiasmuecksch** [gaearon/babel-plugin-react-transform#98]
Hey there,

I tried the following snippet:

```
class Car {
  startEngine() {
    console.log("Engine started!");
  }
}

class Ferraro extends Car {
  static myStaticProp = 21;
  
  logStatic() {
    console.log(this.myStaticProp);
  }
}



var car1 = new Ferraro();
car1.logStatic();
```

I compiled it via babel with es2015 and stage-0. When I run the resulting code, the last line echoes `undefined`.

**Comment by dozoisch** [comment]
What happens if you do `Ferraro.myStaticProp` instead. I don't think static are accessible from the instance directly.

**Comment by tobiasmuecksch** [comment]
Well, that is contradictory to the static properties one might be used to in other languages like Java.

**Comment by Marsup** [comment]
This is exactly like that in C# and C++, maybe Java is the exception and not the norm.

**Comment by tobiasmuecksch** [comment]
@Marsup Thank you for the clarification. Sometime one is tempted to believe Java is the overall standard 😐
